spring:
  application.name: conichi-challenge
server.port: 8081

currency-api:
  url: http://apilayer.net/api
  apiKey: 9abba7ce33bc93ff4062496489e510ce # TODO: externalize api keys injection through docker volume
vat-api:
  url: https://api.cloudmersive.com/validate/vat
  apiKey: 97cd67e2-ed9a-47c2-9eff-9b5b0ce31e1f # TODO: externalize api keys injection through docker volume